
   
     CREATE TABLE "DEMO_TEAMB"."TIPOS_VEHICULOS" 
   (	"TIPO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"TIPO_DESCRIPCION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"TIPO_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("TIPO_ID")
     );
     
       CREATE TABLE "DEMO_TEAMB"."DESECHOS" 
   (	"DESECHO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"DESECHO_DESCRIPCION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DESECHO_ESTADO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE , 
	"DESECHO_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("DESECHO_ID")
     );
     
        CREATE TABLE "DEMO_TEAMB"."MUNICIPIOS" 
   (	"MUNICIPIO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"MUNICIPIO_CODIGO_POSTAL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MUNICIPIO_ESTADO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"MUNICIPIO_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("MUNICIPIO_ID")
   );
   
   
  CREATE TABLE "DEMO_TEAMB"."RUTAS" 
   (	"RUTA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"RUTA_DESCRIPCION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"RUTA_ESTADO" NUMBER(1,0) NOT NULL ENABLE, 
	"RUTA_FECHA_FINALIZACION" DATE NOT NULL ENABLE, 
	"RUTA_FECHA_INICIO" DATE NOT NULL ENABLE, 
	"RUTA_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"MUNICIPIO_ID" NUMBER(19,0), 
	 PRIMARY KEY ("RUTA_ID"), 
	 CONSTRAINT "FK_RUTA_MUNICIPIO" FOREIGN KEY ("MUNICIPIO_ID")
	  REFERENCES "DEMO_TEAMB"."MUNICIPIOS" ("MUNICIPIO_ID"));


     
  CREATE TABLE "DEMO_TEAMB"."CONTRATISTAS" 
   (	"CONTRATISTA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CONTRATISTA_CELULAR" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTRATISTA_CONTRASENA" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTRATISTA_CORREO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTRATISTA_DIRECCION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTRATISTA_FECHA_CREACION" DATE NOT NULL ENABLE, 
	"CONTRATISTA_NIT" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTRATISTA_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTRATISTA_ULTIMA_FACTURACION" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("CONTRATISTA_ID"), 
	 CONSTRAINT "U_CONTRATISTA_NIT" UNIQUE ("CONTRATISTA_NIT"), 
	 CONSTRAINT "U_CONTRATISTA_CORREO" UNIQUE ("CONTRATISTA_CELULAR")
     );
     
    
  CREATE TABLE "DEMO_TEAMB"."CONTRATISTAS_TARIFAN_DESECHOS" 
   (	"CONTRATISTAS_TARIFAN_DESECHOS_PRECIO_KILO" FLOAT(126) NOT NULL ENABLE, 
	"DESECHO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CONTRATISTA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("CONTRATISTA_ID", "DESECHO_ID"), 
	 CONSTRAINT "FK_DESECHO_TARIFADO" FOREIGN KEY ("DESECHO_ID")
	  REFERENCES "DEMO_TEAMB"."DESECHOS" ("DESECHO_ID"), 
	 CONSTRAINT "FK_CONTRATISTA_TARIFA_DESECHO" FOREIGN KEY ("CONTRATISTA_ID")
	  REFERENCES "DEMO_TEAMB"."CONTRATISTAS" ("CONTRATISTA_ID")) ;


     
     
  CREATE TABLE "DEMO_TEAMB"."VEHICULOS" 
   (	"VEHICULO_ID" NUMBER(19,0) NOT NULL ENABLE,
	"VEHICULO_FECHA_CREACION" DATE NOT NULL ENABLE, 
	"VEHICULO_MARCA" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"VEHICULO_MODELO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"VEHICULO_PESO" FLOAT(126) NOT NULL ENABLE, 
	"VEHICULO_PLACA" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTRATISTA_ID" NUMBER(19,0), 
	"RUTA_ID" NUMBER(19,0), 
	"TIPO_ID" NUMBER(19,0), 
     "VEHICULO_ESTADO" NUMBER(1,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("VEHICULO_ID"), 
	 CONSTRAINT "FK_VEHICULO_CONTRATISTA" FOREIGN KEY ("CONTRATISTA_ID")
	  REFERENCES "DEMO_TEAMB"."CONTRATISTAS" ("CONTRATISTA_ID"), 
	 CONSTRAINT "FK_VEHICULO_RUTA" FOREIGN KEY ("RUTA_ID")
	  REFERENCES "DEMO_TEAMB"."RUTAS" ("RUTA_ID"), 
	 CONSTRAINT "FK_VEHICULO_TIPO" FOREIGN KEY ("TIPO_ID")
	  REFERENCES "DEMO_TEAMB"."TIPOS_VEHICULOS" ("TIPO_ID") 
   ) ;
   
   
  CREATE TABLE "DEMO_TEAMB"."CONDUCTORES" 
   (	"CONDUCTOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CONDUCTOR_APELLIDO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONDUCTOR_CELULAR" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONDUCTOR_CORREO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONDUCTOR_DOCUMENTO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONDUCTOR_ESTADO" NUMBER(1,0) NOT NULL ENABLE, 
	"CONDUCTOR_FECHA_NACIMIENTO" DATE NOT NULL ENABLE, 
	"CONDUCTOR_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTRATISTA_ID" NUMBER(19,0), 
	 PRIMARY KEY ("CONDUCTOR_ID"),
	 CONSTRAINT "FK_CONDUCTOR_CONTRISTA" FOREIGN KEY ("CONTRATISTA_ID")
	  REFERENCES "DEMO_TEAMB"."CONTRATISTAS" ("CONTRATISTA_ID"));

     
    
  CREATE TABLE "DEMO_TEAMB"."CENTROS_DISPOSICION" 
   (	"CENTRO_DISPOSICION_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CENTRO_DISPOSICION_CELULAR" VARCHAR2(255 BYTE), 
	"CENTRO_DISPOSICION_CORREO" VARCHAR2(255 BYTE), 
	"CENTRO_DISPOSICION_DIRECCION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CENTRO_DISPOSICION_ESTADO" NUMBER(1,0) DEFAULT 1, 
	"CENTRO_DISPOSICION_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"MUNICIPIO_ID" NUMBER(19,0), 
	 PRIMARY KEY ("CENTRO_DISPOSICION_ID"),
	 CONSTRAINT "FK_CENTRO_DISPOSICION_MUNICIPIO" FOREIGN KEY ("MUNICIPIO_ID")
	  REFERENCES "DEMO_TEAMB"."MUNICIPIOS" ("MUNICIPIO_ID"));
      
      
  CREATE TABLE "DEMO_TEAMB"."CENTROS_DISPOSICION_LIMITAN_DESECHOS" 
   (	"CENTROS_DISPOSICION_LIMITAN_DESECHOS_COSTO_EXCESO" NUMBER(10,0) NOT NULL ENABLE, 
	"CENTROS_DISPOSICION_LIMITAN_DESECHOS_PESO_MAXIMO" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CENTRO_DISPOSICION_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"DESECHO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 CONSTRAINT "FK_VEHICULO_LIMITADO" FOREIGN KEY ("TIPO_ID")
	  REFERENCES "DEMO_TEAMB"."TIPOS_VEHICULOS" ("TIPO_ID"), 
	 CONSTRAINT "FK_CENTRO_DISPOSICION_LIMITANDO" FOREIGN KEY ("CENTRO_DISPOSICION_ID")
	  REFERENCES "DEMO_TEAMB"."CENTROS_DISPOSICION" ("CENTRO_DISPOSICION_ID"), 
	 CONSTRAINT "FK_DESECHO_LIMITADO" FOREIGN KEY ("DESECHO_ID")
	  REFERENCES "DEMO_TEAMB"."DESECHOS" ("DESECHO_ID")) ;


      
      
  CREATE TABLE "DEMO_TEAMB"."TRABAJADORES" 
   (	"TRABAJADOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"TRABAJADOR_APELLIDO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"TRABAJADOR_CELULAR" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"TRABAJADOR_CONTRASENA" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"TRABAJADOR_CORREO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"TRABAJADOR_DIRECCION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"TRABAJADOR_DOCUMENTO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"TRABAJADOR_ESTADO" NUMBER(1,0) NOT NULL ENABLE, 
	"TRABAJADOR_FECHA_INGRESO" DATE NOT NULL ENABLE, 
	"TRABAJADOR_FECHA_NACIMIENTO" DATE NOT NULL ENABLE, 
	"TRABAJADOR_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"TRABAJADOR_TIPO" NUMBER(1,0) NOT NULL ENABLE, 
	"CENTRO_DISPOSICION_ID" NUMBER(19,0), 
	 PRIMARY KEY ("TRABAJADOR_ID"), 
	 CONSTRAINT "U_TRABAJADOR_DOCUMENTO" UNIQUE ("TRABAJADOR_DOCUMENTO"),
	 CONSTRAINT "U_TRABAJADOR_CELULAR" UNIQUE ("TRABAJADOR_CELULAR"),
	 CONSTRAINT "U_TRABAJADOR_CORREO" UNIQUE ("TRABAJADOR_CORREO"),
	 CONSTRAINT "FK_TRABAJADOR_CENTRO" FOREIGN KEY ("CENTRO_DISPOSICION_ID")
	  REFERENCES "DEMO_TEAMB"."CENTROS_DISPOSICION" ("CENTRO_DISPOSICION_ID")
      );




  CREATE TABLE "DEMO_TEAMB"."CELDAS" 
   (	"CELDA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CELDA_CAPACIDAD_TOTAL" NUMBER(10,0) NOT NULL ENABLE, 
	"CELDA_CAPACIDAD_USADA" NUMBER(10,0) NOT NULL ENABLE, 
	"CELDA_ESTADO" NUMBER(1,0) NOT NULL ENABLE, 
	"CELDA_NOMBRE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CENTRO_DISPOSICION_ID" NUMBER(19,0), 
	 PRIMARY KEY ("CELDA_ID"),
	 CONSTRAINT "FK_CELDA_CENTRO" FOREIGN KEY ("CENTRO_DISPOSICION_ID")
	  REFERENCES "DEMO_TEAMB"."CENTROS_DISPOSICION" ("CENTRO_DISPOSICION_ID") ON DELETE SET NULL
   );
   
   
  CREATE TABLE "DEMO_TEAMB"."CELDAS_ADMITEN_DESECHOS" 
   (	"CELDA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"DESECHO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("CELDA_ID", "DESECHO_ID"), 
	 CONSTRAINT "FK_CELDA_ADMITIENDO" FOREIGN KEY ("CELDA_ID")
	  REFERENCES "DEMO_TEAMB"."CELDAS" ("CELDA_ID"), 
	 CONSTRAINT "FK_CELDA_ADMITE_DESECHO" FOREIGN KEY ("DESECHO_ID")
	  REFERENCES "DEMO_TEAMB"."DESECHOS" ("DESECHO_ID"));
      
      
      
  CREATE TABLE "DEMO_TEAMB"."INGRESOS" 
   (	"INGRESO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"INGRESO_FECHA" DATE NOT NULL ENABLE, 
	"INGRESO_PESO" FLOAT(126) NOT NULL ENABLE, 
	"INGRESO_PESO_SOBRECARGA" FLOAT(126) NOT NULL ENABLE, 
	"INGRESO_VALOR_SOBRECARGA" NUMBER(10,0), 
	"INGRESO_VALOR_TRANSPORTE" NUMBER(10,0),
	"INGRESO_ESTADO" NUMBER(1,0) NOT NULL ENABLE, 
	"CELDA_ID" NUMBER(19,0), 
	"CONDUCTOR_ID" NUMBER(19,0), 
	"DESECHO_ID" NUMBER(19,0), 
	"FACTURA_ID" NUMBER(19,0), 
	"TRABAJADOR_ID" NUMBER(19,0), 
	"VEHICULO_ID" NUMBER(19,0), 
	 PRIMARY KEY ("INGRESO_ID"),
	 CONSTRAINT "FK_INGRESO_CELDA" FOREIGN KEY ("CELDA_ID")
	  REFERENCES "DEMO_TEAMB"."CELDAS" ("CELDA_ID"), 
	 CONSTRAINT "FK_INGRESO_CONDUCTOR" FOREIGN KEY ("CONDUCTOR_ID")
	  REFERENCES "DEMO_TEAMB"."CONDUCTORES" ("CONDUCTOR_ID"), 
	 CONSTRAINT "FK_INGRESO_DESECHO" FOREIGN KEY ("DESECHO_ID")
	  REFERENCES "DEMO_TEAMB"."DESECHOS" ("DESECHO_ID"), 
	 CONSTRAINT "FK_INGRESO_FACTURA" FOREIGN KEY ("FACTURA_ID")
	  REFERENCES "DEMO_TEAMB"."FACTURAS" ("FACTURA_ID") ENABLE, 
	 CONSTRAINT "FK_INGRESO_TRABAJADOR" FOREIGN KEY ("TRABAJADOR_ID")
	  REFERENCES "DEMO_TEAMB"."TRABAJADORES" ("TRABAJADOR_ID"), 
	 CONSTRAINT "FK_INGRESO_VEHICULO" FOREIGN KEY ("VEHICULO_ID")
	  REFERENCES "DEMO_TEAMB"."VEHICULOS" ("VEHICULO_ID")
   ) ;

  CREATE INDEX "DEMO_TEAMB"."IDX_INGRESOS_FACTURA" ON "DEMO_TEAMB"."INGRESOS" ("FACTURA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

  CREATE INDEX "DEMO_TEAMB"."IDX_INGRESOS_FECHA" ON "DEMO_TEAMB"."INGRESOS" ("INGRESO_FECHA" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

  CREATE INDEX "DEMO_TEAMB"."IDX_INGRESOS_VEHICULO" ON "DEMO_TEAMB"."INGRESOS" ("VEHICULO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  
  
  
  CREATE TABLE "DEMO_TEAMB"."FACTURAS" 
   (	"FACTURA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"FACTURA_COSTO_TRANSPORTE" FLOAT(126) NOT NULL ENABLE, 
	"FACTURA_DESCUENTO" FLOAT(126) NOT NULL ENABLE, 
	"FACTURA_FIN_PERIODO" DATE NOT NULL ENABLE, 
	"FACTURA_INICIO_PERIODO" DATE NOT NULL ENABLE, 
	"CENTRO_DISPOSICION_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CONTRATISTA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("FACTURA_ID"), 
	 CONSTRAINT "FK_FACTURA_CONTRATISTA" FOREIGN KEY ("CONTRATISTA_ID")
	  REFERENCES "DEMO_TEAMB"."CONTRATISTAS" ("CONTRATISTA_ID"), 
	 CONSTRAINT "FK_FACTURA_CENTRO" FOREIGN KEY ("CENTRO_DISPOSICION_ID")
	  REFERENCES "DEMO_TEAMB"."CENTROS_DISPOSICION" ("CENTRO_DISPOSICION_ID")
   );

  CREATE INDEX "DEMO_TEAMB"."IDX_FACTURAS_CENTRO_DISPOSICION" ON "DEMO_TEAMB"."FACTURAS" ("CENTRO_DISPOSICION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

  CREATE INDEX "DEMO_TEAMB"."IDX_FACTURAS_CONTRATISTA" ON "DEMO_TEAMB"."FACTURAS" ("CONTRATISTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

  CREATE INDEX "DEMO_TEAMB"."IDX_FACTURAS_RANGO_FECHA" ON "DEMO_TEAMB"."FACTURAS" ("FACTURA_INICIO_PERIODO" DESC, "FACTURA_FIN_PERIODO" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;





