--CREACION DE LA DB

-- USER SQL
CREATE USER RECOLECTA
ALTER USER "RECOLECTA" IDENTIFIED BY "6488" 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "RECOLECTA" ;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "RECOLECTA" ;
GRANT DROP ANY TRIGGER TO "RECOLECTA" ;
GRANT CREATE TRIGGER TO "RECOLECTA" ;
GRANT CREATE ANY SEQUENCE TO "RECOLECTA" ;
GRANT CREATE SESSION TO "RECOLECTA" ;
GRANT DELETE ANY TABLE TO "RECOLECTA" ;
GRANT CREATE TABLE TO "RECOLECTA" ;
GRANT CREATE TABLESPACE TO "RECOLECTA" ;
GRANT DROP ANY TYPE TO "RECOLECTA" ;
GRANT EXECUTE ANY PROCEDURE TO "RECOLECTA" ;
GRANT CREATE SEQUENCE TO "RECOLECTA" ;
GRANT CREATE ANY TRIGGER TO "RECOLECTA" ;
GRANT CREATE ANY TABLE TO "RECOLECTA" ;
GRANT CREATE ANY TYPE TO "RECOLECTA" ;
GRANT DROP TABLESPACE TO "RECOLECTA" ;